'use client';
import Link from 'next/link';
import {Suspense,useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {levels} from '@/lib/curriculum';
import {createClient} from '@/lib/supabase/client';
type Q={id:string;code:string;garden_id:string;dimension:string;prompt:string;answer:any};
function QuizBank(){
 const sp=useSearchParams();const initial=sp.get('garden')||'N01';
 const [garden,setGarden]=useState(initial);const [qs,setQs]=useState<Q[]>([]);const [active,setActive]=useState<Q|null>(null);const [response,setResponse]=useState('');const [scores,setScores]=useState<Record<string,number>>({});const [msg,setMsg]=useState('');const [loading,setLoading]=useState(true);
 const all=useMemo(()=>levels.flatMap(l=>l.gardens.map(g=>({...g,level:l.name}))),[]);
 useEffect(()=>{const controller=new AbortController();(async()=>{setLoading(true);setMsg('');setQs([]);setActive(null);setResponse('');try{const r=await fetch('/api/quiz-bank?garden='+encodeURIComponent(garden),{cache:'no-store',signal:controller.signal});const payload=await r.json();if(!r.ok)throw new Error(payload?.error||'Unable to load assessment items.');const rows=Array.isArray(payload)?payload:[];setQs(rows);if(rows.length)setActive(rows[0]);else setMsg('No assessment items returned for this garden.');}catch(e:any){if(e?.name!=='AbortError')setMsg(e?.message||'Unable to load assessment items.');}finally{if(!controller.signal.aborted)setLoading(false);}})();return()=>controller.abort();},[garden]);
 async function submit(){if(!active)return;const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){setMsg('Sign in as a learner to save this response. Preview remains available.');return}const [{data:en},{data:qrow,error:qerr}]=await Promise.all([s.from('growmeal_enrollments').select('class_id').eq('learner_id',user.id).eq('status','active').limit(1).maybeSingle(),s.from('growmeal_quizzes').select('id').eq('code',active.code).maybeSingle()]);if(qerr||!qrow?.id){setMsg(qerr?.message||'The canonical AQ record could not be linked.');return}const {error}=await s.from('growmeal_assessment_results').insert({quiz_id:qrow.id,learner_id:user.id,class_id:en?.class_id||null,response_text:response,response_json:{self_rating:scores[active.id]??null,quiz_code:active.code,garden_id:garden},status:'submitted',finalized:false});setMsg(error?error.message:'Response submitted for teacher review.');if(!error)setResponse('');}
 return <><div className="eyebrow">AQ-001–AQ-500 · LIVE ASSESSMENT BANK</div><h1>Interactive Quiz & Assessment</h1><p className="lead">Each sub-garden has ten assessment items across knowledge, practical competence, investigation/data skills and mission-based problem solving.</p><select className="big-select" value={garden} onChange={e=>setGarden(e.target.value)}>{all.map(g=><option key={g.id} value={g.id}>{g.level} · {g.name}</option>)}</select><p className="form-msg">{loading?'Loading assessment items…':qs.length?`${qs.length} assessment items loaded for this garden.`:msg||'No assessment items returned.'}</p><div className="quiz-layout"><div className="quiz-list">{qs.map(q=><button key={q.code} className={active?.code===q.code?'selected':''} onClick={()=>{setActive(q);setResponse('');setMsg('')}}><span>{q.code}</span><b>{q.dimension.replaceAll('_',' ')}</b><small>{q.prompt}</small></button>)}</div><div className="panel quiz-workspace">{active?<><div className="eyebrow">{active.code} · {active.dimension.replaceAll('_',' ')}</div><h2>{active.prompt}</h2><textarea rows={7} placeholder="Enter the learner response or teacher observation…" value={response} onChange={e=>setResponse(e.target.value)}/><label className="rating-label">Self/teacher working rating</label><div className="rating">{[0,1,2,3].map(n=><button className={scores[active.id]===n?'on':''} key={n} onClick={()=>setScores({...scores,[active.id]:n})}>{n}<small>{['Not demonstrated','Beginning','Developing','Secure'][n]}</small></button>)}</div><div className="rubric-note"><b>Teacher guidance</b><p>{active.answer?.guidance||'Use the level-appropriate 0–3 evidence rubric.'}</p></div><div className="hero-actions"><button className="btn primary" disabled={!response.trim()} onClick={submit}>Submit response</button><Link className="btn" href={`/gardens/${garden}/assessments/${active.code}`}>Open full AQ record</Link></div>{msg&&<p className="form-msg">{msg}</p>}</>:<div className="empty-state"><b>{loading?'Loading assessment items…':'No assessment item available'}</b><p>{loading?'The canonical AQ bank is being loaded.':msg||'No AQ content was returned.'}</p></div>}</div></div></>;
}
export default function Quizzes(){return <Suspense><QuizBank/></Suspense>}