'use client';
import Link from 'next/link';
import {Suspense,useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {levels} from '@/lib/curriculum';
import {createClient} from '@/lib/supabase/client';
type C={id:string;code:string;garden_id:string;title:string;scenario:string;task:string;evidence:string;success_criteria:string;extension?:string;safety:string};
function ChallengeBank(){
 const sp=useSearchParams();const initial=sp.get('garden')||'N01';const [garden,setGarden]=useState(initial);const [rows,setRows]=useState<C[]>([]);const [active,setActive]=useState<C|null>(null);const [text,setText]=useState('');const [msg,setMsg]=useState('');const [loading,setLoading]=useState(true);const all=useMemo(()=>levels.flatMap(l=>l.gardens.map(g=>({...g,level:l.name}))),[]);
 useEffect(()=>{const controller=new AbortController();(async()=>{setLoading(true);setMsg('');setRows([]);setActive(null);try{const r=await fetch('/api/challenge-bank?garden='+encodeURIComponent(garden),{cache:'no-store',signal:controller.signal});const payload=await r.json();if(!r.ok)throw new Error(payload?.error||'Unable to load challenges.');const data=Array.isArray(payload)?payload:[];setRows(data);if(data.length)setActive(data[0]);else setMsg('No Food Smart Challenges returned for this garden.');}catch(e:any){if(e?.name!=='AbortError')setMsg(e?.message||'Unable to load challenges.');}finally{if(!controller.signal.aborted)setLoading(false);}})();return()=>controller.abort();},[garden]);
 async function submit(){if(!active)return;const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){setMsg('Sign in as a learner to submit challenge evidence. Preview remains available.');return}const [{data:en},{data:crow,error:cerr}]=await Promise.all([s.from('growmeal_enrollments').select('class_id').eq('learner_id',user.id).eq('status','active').limit(1).maybeSingle(),s.from('growmeal_challenges').select('id').eq('code',active.code).maybeSingle()]);if(cerr||!crow?.id){setMsg(cerr?.message||'The canonical FSC record could not be linked.');return}const {error}=await s.from('growmeal_challenge_submissions').insert({challenge_id:crow.id,class_id:en?.class_id||null,learner_id:user.id,submission_text:text,status:'submitted'});setMsg(error?error.message:'Challenge evidence submitted for teacher review.');if(!error)setText('');}
 return <><div className="eyebrow">FSC-001–FSC-500 · LIVE CHALLENGE BANK</div><h1>Food Smart Challenges</h1><p className="lead">Each sub-garden contains ten evidence-based food and resource challenges. Select a challenge to view its scenario, task, evidence requirements, success criteria and safety guidance.</p><select className="big-select" value={garden} onChange={e=>setGarden(e.target.value)}>{all.map(g=><option key={g.id} value={g.id}>{g.level} · {g.name}</option>)}</select><p className="form-msg">{loading?'Loading Food Smart Challenges…':rows.length?`${rows.length} challenges loaded for this garden.`:msg||'No challenges returned.'}</p><div className="challenge-grid">{rows.map(c=><button key={c.code} className={active?.code===c.code?'selected':''} onClick={()=>{setActive(c);setText('');setMsg('')}}><span>{c.code}</span><b>{c.title}</b><small>{c.scenario}</small></button>)}</div>{active&&<div className="drawer"><button className="drawer-close" onClick={()=>setActive(null)}>×</button><div className="eyebrow">{active.code}</div><h2>{active.title}</h2><div className="challenge-detail"><b>Scenario</b><p>{active.scenario}</p><b>Your task</b><p>{active.task}</p><b>Evidence</b><p>{active.evidence}</p><b>Success criteria</b><p>{active.success_criteria}</p>{active.extension&&<><b>Extension</b><p>{active.extension}</p></>}<b>Safety</b><p>{active.safety}</p></div><textarea rows={7} placeholder="Describe your evidence, calculation, decision or reflection…" value={text} onChange={e=>setText(e.target.value)}/><div className="hero-actions"><button className="btn primary" disabled={!text.trim()} onClick={submit}>Submit challenge evidence</button><Link className="btn" href={`/gardens/${garden}/challenges/${active.code}`}>Open full challenge record</Link></div>{msg&&<p className="form-msg">{msg}</p>}</div>}</>;
}
export default function Challenges(){return <Suspense><ChallengeBank/></Suspense>}