export type Level = { id:string; name:string; age:string; progression:string; gardens: Garden[] };
export type Garden = { id:string; name:string; focus:string; quizRange:string; challengeRange:string; practicalRange:string; missionRange:string };
const mk=(id:string,name:string,focus:string,start:number):Garden=>({id,name,focus,quizRange:`AQ-${String(start).padStart(3,'0')}–AQ-${String(start+9).padStart(3,'0')}`,challengeRange:`FSC-${String(start).padStart(3,'0')}–FSC-${String(start+9).padStart(3,'0')}`,practicalRange:`PA-${String(start).padStart(3,'0')}–PA-${String(start+9).padStart(3,'0')}`,missionRange:`GM-${String(start).padStart(3,'0')}–GM-${String(start+9).padStart(3,'0')}`});
export const levels:Level[]=[
{id:'nursery',name:'Nursery 1–3',age:'Early Years',progression:'LOOK → NAME → COUNT → MATCH → CARE → TELL',gardens:[
mk('N01','Alphabet Garden','Letters, food names and crop recognition',1),mk('N02','Number Garden','Numbers and quantities',11),mk('N03','Geometry Garden','Shapes and garden spaces',21),mk('N04','Leaf Garden','Leaf form and change',31),mk('N05','Butterfly Garden','Flowers and garden visitors',41),mk('N06','ReBottle Garden','Reused bottle planters',51),mk('N07','MicroGrow Garden','Tiny seedlings',61),mk('N08','Mini Table Garden','Small table-top growing',71),mk('N09','Sack Garden','Food production in sacks',81),mk('N10','Discovery Garden','Integrated discovery learning',91)]},
{id:'primary-1-3',name:'Primary 1–3',age:'Foundation Primary',progression:'OBSERVE → MEASURE → COMPARE → RECORD → EXPLAIN',gardens:[
mk('P11','Alphabet Food Garden','Food vocabulary and crop identification',101),mk('P12','Number Food Garden','Counting and simple garden data',111),mk('P13','Geometry Garden','Garden geometry and food shapes',121),mk('P14','Leaf Garden','Leaf identification and comparison',131),mk('P15','Pollinator Garden','Flowers, fruits, seeds and pollinators',141),mk('P16','Raised Food Garden','Planting, crop care and harvest',151),mk('P17','ReBottle Wall Garden','Vertical reused-container growing',161),mk('P18','Sack GrowBag Garden','Alternative container production',171),mk('P19','Ground Production Garden','Soil-based crop production',181),mk('P20','Discovery Production Garden','Integrated food-production learning',191)]},
{id:'primary-4-6',name:'Primary 4–6',age:'Upper Primary',progression:'QUESTION → MEASURE → INVESTIGATE → ANALYZE → EXPLAIN',gardens:[
mk('P21','Raised Food Garden','Crop growth, spacing and harvest records',201),mk('P22','Geometry Garden','Area, spacing and crop arrangement',211),mk('P23','Grid Experiment Garden','Controlled garden comparisons',221),mk('P24','Keyhole Garden','Access and resource flow',231),mk('P25','Compost Garden','Decomposition and compost management',241),mk('P26','Gravity Drip Garden','Gravity-fed irrigation',251),mk('P27','Vertical Garden','Multi-level production',261),mk('P28','Crop Rotation Garden','Crop sequence and diversity',271),mk('P29','Water-Smart Garden','Water movement and productivity',281),mk('P30','Intro Soilless Garden','Introductory soilless production',291)]},
{id:'jss',name:'JSS 1–3',age:'Junior Secondary',progression:'DEFINE → HYPOTHESIZE → EXPERIMENT → QUANTIFY → ANALYZE → RECOMMEND',gardens:[
mk('J31','Production Garden','Crop production performance',301),mk('J32','Raised Systems Garden','Raised-system performance',311),mk('J33','Grid Experiment Garden','Controlled garden comparisons',321),mk('J34','Crop Rotation Garden','Rotation planning and soil-cover logic',331),mk('J35','Intercropping Garden','Two-crop interactions',341),mk('J36','Water-Smart Garden','Water movement and productivity',351),mk('J37','Compost & Soil Garden','Compost-soil processes',361),mk('J38','Soilless Learning Garden','Recirculating soilless operation',371),mk('J39','Sensor-Ready Garden','Sensor measurement quality',381),mk('J40','Applied Systems Garden','Whole-system relationships',391)]},
{id:'sss',name:'SSS 1–3',age:'Senior Secondary',progression:'FRAME → DESIGN → INSTRUMENT → MODEL → VALIDATE → EVALUATE → OPTIMIZE',gardens:[
mk('S41','Advanced Production Garden','Advanced production efficiency',401),mk('S42','Crop Trial Garden','Replicated crop trials',411),mk('S43','Controlled Experiment Garden','Causal experimental design',421),mk('S44','Irrigation Engineering Garden','Hydraulic design and performance',431),mk('S45','Water Productivity Garden','Water balance and productivity',441),mk('S46','Advanced Soilless Garden','Recirculating soilless control',451),mk('S47','Sensor & Monitoring Garden','Instrumentation and monitoring quality',461),mk('S48','Smart Irrigation Demonstrator','Feedback irrigation control',471),mk('S49','Research & Design Garden','Engineering design decisions',481),mk('S50','Integrated Food Systems Laboratory','Integrated food-water-energy systems',491)]}
];
export const resourceTypes=['Student Workbook','Observation / Research Journal','Concept Flashcards','Practical Activity Cards','Garden Mission Cards','Assessment & Quiz','Teacher Guide','12-Week Lesson Plan','Ingredient Lab','Farm-to-Food','Food Smart Challenge','Food Smart Passport','Teacher Demonstration Cards'];
