export const downloads=[
{title:'50-Garden Master Resource Matrix',type:'Master Matrix',level:null,path:'/resources/GrowMeal_50_Garden_Master_Resource_Matrix.xlsx'},
{title:'12-Week Master Curriculum Map',type:'Curriculum Map',level:null,path:'/resources/MASTER_12_Week_Lesson_Plan_Curriculum_Map.csv'},
{title:'GrowMeal Master Teacher Guide',type:'Teacher Guide',level:null,path:'/resources/GrowMeal_Master_Teacher_Guide.pdf'},
{title:'50-Garden Design & Installation Technical Manual',type:'Technical Manual',level:null,path:'/resources/GrowMeal_50_Garden_Design_Installation_Technical_Manual.pdf'},
{title:'School Implementation & Garden Operations Manual',type:'School Operations',level:null,path:'/resources/GrowMeal_School_Implementation_Garden_Operations_Manual.pdf'},
{title:'Monitoring, Evaluation & Certification Manual',type:'M&E',level:null,path:'/resources/GrowMeal_Monitoring_Evaluation_Certification_Manual.pdf'},
{title:'Teacher Training & Certification Manual',type:'Teacher Training',level:null,path:'/resources/GrowMeal_Teacher_Training_Certification_Manual.pdf'},
{title:'Procurement & Budgeting School Package Manual',type:'Procurement',level:null,path:'/resources/GrowMeal_Procurement_Budgeting_School_Package_Manual.pdf'},
{title:'Nursery Garden Observation Journal',type:'Student Journal',level:'nursery',path:'/resources/GrowMeal_Nursery_Garden_Observation_Journal.pdf'},
{title:'Primary 1–3 Garden Observation & Learning Journal',type:'Student Journal',level:'primary-1-3',path:'/resources/GrowMeal_Primary_1_3_Garden_Observation_Learning_Journal.pdf'},
{title:'Primary 4–6 Garden Investigation Journal',type:'Student Journal',level:'primary-4-6',path:'/resources/GrowMeal_Primary_4_6_Garden_Investigation_Journal.pdf'},
{title:'Alphabet Garden Teacher Course',type:'Teacher Course',level:'nursery',path:'/resources/AgriShine_Alphabet_Garden_Teacher_Course.pdf'},
{title:'Number Garden Teacher Course',type:'Teacher Course',level:'nursery',path:'/resources/AgriShine_Number_Garden_Teacher_Course.pdf'},
{title:'Food Smart Club — Nursery',type:'Food Smart Club',level:'nursery',path:'/resources/Food_Smart_Club_Nursery.pdf'},
{title:'Food Smart Club — Primary',type:'Food Smart Club',level:'primary-1-3',path:'/resources/Food_Smart_Club_Primary.pdf'},
{title:'Food Smart Club — JSS',type:'Food Smart Club',level:'jss',path:'/resources/Food_Smart_Club_JSS.pdf'},
{title:'Food Smart Club — SSS',type:'Food Smart Club',level:'sss',path:'/resources/Food_Smart_Club_SSS.pdf'},
] as const;
