-- GrowMeal MVP starter schema (abridged for app integration)
create extension if not exists "pgcrypto";
create table if not exists schools (id uuid primary key default gen_random_uuid(), name text not null, region text, default_language text default 'en', active boolean default true, created_at timestamptz default now());
create table if not exists profiles (id uuid primary key, school_id uuid references schools(id), full_name text not null, email text, preferred_language text default 'en', created_at timestamptz default now());
create table if not exists growmeal_levels (id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, sort_order int not null);
create table if not exists canonical_gardens (id uuid primary key default gen_random_uuid(), garden_code text unique not null, level_id uuid references growmeal_levels(id), garden_number int not null, name text not null, description text);
create table if not exists classes (id uuid primary key default gen_random_uuid(), school_id uuid references schools(id), level_id uuid references growmeal_levels(id), name text not null, active boolean default true);
create table if not exists curriculum_resources (id uuid primary key default gen_random_uuid(), resource_code text unique not null, resource_type text not null, level_id uuid references growmeal_levels(id), garden_id uuid references canonical_gardens(id), week_number int, title text not null, body text, status text default 'draft');
create table if not exists school_gardens (id uuid primary key default gen_random_uuid(), school_id uuid references schools(id), canonical_garden_id uuid references canonical_gardens(id), status text default 'planned', installed_at date, commissioned_at date, configuration jsonb default '{}'::jsonb);
create table if not exists lesson_deliveries (id uuid primary key default gen_random_uuid(), school_id uuid references schools(id), class_id uuid references classes(id), week_number int not null, planned_date date, delivered_at timestamptz, completion_status text default 'planned', teacher_note text);
create table if not exists evidence (id uuid primary key default gen_random_uuid(), school_id uuid references schools(id), resource_id uuid references curriculum_resources(id), evidence_type text not null, title text, payload jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists assessment_attempts (id uuid primary key default gen_random_uuid(), school_id uuid references schools(id), learner_id uuid, assessment_code text, status text default 'in_progress', final_percentage numeric(6,2), created_at timestamptz default now());
create table if not exists passports (id uuid primary key default gen_random_uuid(), school_id uuid references schools(id), learner_id uuid, level_id uuid references growmeal_levels(id), completion_percentage numeric(6,2) default 0, status text default 'active');
